baseURL = "https://www.RUNTHEHOUSE.co.uk"
languageCode = "en-us"
title = "RUNTHEHOUSE"
disableKinds = ["section", "categories"]
googleAnalytics = "G-4Q78ZRT7GE"
disqusShortname = "cranky-mayer-a22b3f-netlify-app"
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 999
minify = true


[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = ""

[params]
  description = ""
  author = ""
  copyright = ""
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"
  
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "blog"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20


  [[menu.main]]
    identifier = "tags"
    name       = "strava"
    url        = "https://www.strava.com/athletes/70255468"
    weight     = -10